// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ifjo8mQhZShk9MTbJihQ8z9_dBcD4eM',
    appId: '1:722936006845:web:930d2f7507d2e23b8b8fd4',
    messagingSenderId: '722936006845',
    projectId: 'hksc-36aaf',
    authDomain: 'hksc-36aaf.firebaseapp.com',
    storageBucket: 'hksc-36aaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWRBt5QlbEbeAZYn5aYWRTvSNgN6LUGkk',
    appId: '1:722936006845:android:ed84db99ce6f3ccd8b8fd4',
    messagingSenderId: '722936006845',
    projectId: 'hksc-36aaf',
    storageBucket: 'hksc-36aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwXUg2RKZafrYjCq3Z3TDuu2hRPWNz-M',
    appId: '1:722936006845:ios:8629d2e5f1ca11fa8b8fd4',
    messagingSenderId: '722936006845',
    projectId: 'hksc-36aaf',
    storageBucket: 'hksc-36aaf.firebasestorage.app',
    iosBundleId: 'com.example.hkksccc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwXUg2RKZafrYjCq3Z3TDuu2hRPWNz-M',
    appId: '1:722936006845:ios:8629d2e5f1ca11fa8b8fd4',
    messagingSenderId: '722936006845',
    projectId: 'hksc-36aaf',
    storageBucket: 'hksc-36aaf.firebasestorage.app',
    iosBundleId: 'com.example.hkksccc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0ifjo8mQhZShk9MTbJihQ8z9_dBcD4eM',
    appId: '1:722936006845:web:91b26508871a049b8b8fd4',
    messagingSenderId: '722936006845',
    projectId: 'hksc-36aaf',
    authDomain: 'hksc-36aaf.firebaseapp.com',
    storageBucket: 'hksc-36aaf.firebasestorage.app',
  );
}
